application: usechillbrain
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /scrape
  script: brains/scraper.py
  login: admin

- url: /worker
  script: brains/scraper.py
  login: admin
  
- url: /test/test.*
  script: test/gaeunit.py  

- url: /.*
  script: main.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

builtins:
- appstats: on
- datastore_admin: on