application: usechillbrain
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /scrape
  script: brains/scraper.py
  login: admin

- url: /worker
  script: brains/scraper.py
  login: admin
  
- url: /test/test.*
  script: test/gaeunit.py  

- url: /migrateImages
  script: util/migrateImageToCBImage.py
  login: admin

- url: /.*
  script: main.py

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on
