application: efpscrape
version: 4
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /scrape
  script: brains/scraper.py
  login: admin

- url: /worker
  script: brains/scraper.py
  login: admin
  
- url: /test/test.*
  script: test/gaeunit.py  

- url: /.*
  script: main.py

builtins:
- appstats: off
- datastore_admin: on